# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :unitTests do |options|
    xcode_select("/Applications/Xcode_15.0.1.app")

    clear_derived_data
      
    run_tests(
      workspace: "ExerciseTracker.xcodeproj",
      device: "iPhone SE (3rd generation)",
      result_bundle: true,
      scheme: options[:scheme],
      testplan: options[:testplan]
    )
  end

  desc "Run Tests"
    lane :uiTests do |options|
      xcode_select("/Applications/Xcode_14.3.1.app")

      clear_derived_data
      
      run_tests(
        workspace: "ExerciseTracker.xcodeproj",
        device: "iPhone SE (3rd generation) (16.4)",
        result_bundle: true,
        scheme: options[:scheme],
        testplan: options[:testplan]
      )
    end

end
